apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pred-main-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=moonysun1314/ml-model
    argocd-image-updater.argoproj.io/write-back-method: git:secret:git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: pred-main
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pred-main/base
    repoURL: https://github.com/sunnymoon1314/ce5-group5-capstone.git
    targetRevision: main
  syncPolicy:
    automated: {}
