# https://stackoverflow.com/questions/73300108/how-can-i-add-nodeport-in-kustomize-overlays.
apiVersion: v1
kind: Service
metadata:
  name: pred-main-service
  namespace: classifier
  labels:
    app.kubernetes.io/name: pred-main
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5001
      nodePort: 30101
  selector:
    app.kubernetes.io/name: pred-main
