name: Test login to all cloud platforms.

on:
  workflow_dispatch:
    inputs:
      selected-environment:
        type: environment
        description: Select the environment.

# defaults:
#  run:
#    working-directory: ./terraform/aws

jobs:
  deploy-to-aws:
    name: Test login credentials of AWS.
    environment: ${{ inputs.selected-environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4

      - name: Configure AWS credentials.
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform.
        uses: hashicorp/setup-terraform@v3

      # Make sure we are in the terraform folder where all the deployment tf files are.
      # terraform -chdir=terraform/aws init
      # - run: |
          # cd ./terraform/aws

      - name: Terraform init.
        run: |
          cd ./terraform/aws
          terraform init

      # - name: Terraform workspace list.
      #  run: terraform workspace list

      # - name: Terraform workspace new environment and select.
      #  run: |
      #    terraform workspace select ${{ inputs.selected-environment }} || terraform workspace new ${{ inputs.selected-environment }}
      #    terraform workspace list

      - name: Terraform plan.
        run: |
          ls -la
          cd ./terraform/aws
          ls -la
          terraform plan -var-file=${{ inputs.selected-environment }}.tfvars

      - name: Terraform apply.
      
        run: |
          cd ./terraform/aws
          terraform apply -var-file=${{ inputs.selected-environment }}.tfvars -auto-approve

      - name: Pause 1min to verify bucket creation.
        run: sleep 60

      - name: Terraform destroy.
        run: |
          cd ./terraform/aws
          terraform destroy -var-file=${{ inputs.selected-environment }}.tfvars -auto-approve

      # - name: Download model???
        # uses: actions/download-artifact@v2
        # with:
          # name: api
      - run: |
          echo "Deploy infrastructures using Terraform..."
