name: Run Python scripts to prepare the dataset, train, test, build the model (pkl format).
# - How to Run Python Scripts in GitHub Action Workflows, Data Engineering With Nick, 1.43K subscribers
#   https://www.youtube.com/watch?v=zk4bSTD8uWM

on:
  push:
    branches:
      - dev
 
jobs:
    # 25.05.2024 Soon: Added snyk-scan job.
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
    if: ${{ always() }}

  prepare-train-build:
    needs: [snyk-scan]
    environment: "dev"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4

      - name: Setup Python 3.12.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Python dependencies.
        run: |
          # python -m pip install --upgrade . botocore boto3 awscli
          echo "Install Python dependencies."
          python -m pip install -r requirements.txt

      - name: Run Python scripts.
        run: |
          # if [ "${{ inputs.action }}" = "prepare" ]; then
          # elif [ "${{ inputs.action }}" = "train-build" ]; then
          # fi
          echo "Running python scripts..."
          python src/prepare.py
          # This will create a *_model.pkl file in the model folder.
          python src/train_build.py

      # https://github.com/actions/upload-artifact/tree/v4
      - uses: actions/upload-artifact@v4
        with:
          name: Trained model artifact.
          # You can use wildcard pattern to specify what files/folders to upload.
          # path: ./model/*.pkl
          path: ./model/*
